In [201]:
import pandas as pd
titanic_df = pd.read_csv("../파이썬_머신러닝_완벽가이드/titanic/train.csv")

In [202]:
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [203]:
print("titanic 변수 type:", type(titanic_df))

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


In [204]:
print("Data Frame의 크기:", titanic_df.shape)

Data Frame의 크기: (891, 12)


In [205]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [206]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [207]:
value_counts = titanic_df["Pclass"].value_counts()
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [208]:
titanic_pclass = titanic_df["Pclass"]
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [209]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [210]:
value_counts = titanic_df["Pclass"].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


## Data Frame과 리스트, 딕셔너리, 넘파이, ndarray 상호 변환

In [211]:
import numpy as np

col_name1 = ["col1"]
list1 = [1,2,3]
array1 = np.array(list1)
print("array1 shape:", array1.shape)
# 리스트를 이용해 DataFrame 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print("1차원 리스트로 만든 DataFrame:\n", df_list1)
# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns =col_name1)
print("1차원 ndarray로 만든 DataFrame:\n", df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [212]:
# 3개의 컬럼명이 필요함
col_name2 = ["col", "col2", "col3"]

# 2행 * 3열 형태의 리스트와 ndarrat를 생선한 뒤 이를 DataFrame으로 변환
array2 = np.arange(start = 1, stop =7)
array2 = array2.reshape(2,3)
list2 = list(array2)
print(array2)
print(list2)
print("array2 shape:", array2.shape)
df_list2 = pd.DataFrame(list2, columns=col_name2)
print("2차원 lsit2로 만든 DataFrame:","\n" , df_list2)
df_array2 = pd.DataFrame(array2, columns = col_name2)
print("2차원 ndarray로 만든 DataFrame:", "\n" , df_array2)

[[1 2 3]
 [4 5 6]]
[array([1, 2, 3]), array([4, 5, 6])]
array2 shape: (2, 3)
2차원 lsit2로 만든 DataFrame: 
    col  col2  col3
0    1     2     3
1    4     5     6
2차원 ndarray로 만든 DataFrame: 
    col  col2  col3
0    1     2     3
1    4     5     6


In [213]:
# key는 문자열 칼럼명으로 매핑, vlaue는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑
dict ={"col1": [1,11], "col2": [2,22], "col3":[3,33]}
df_dict = pd.DataFrame(dict)
print("딕셔너리로 만든 DataFrame:\n", df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [214]:
# DataFrame을 ndarray로 변환
# DataFrame을 vlaues로 ndarray화 할 수 있음.

array3 = df_dict.values
print(df_dict)
print(array3)
print("df_dict.values의 타입:", type(array2), "df_dict.values shape: ", 
     array3.shape)

   col1  col2  col3
0     1     2     3
1    11    22    33
[[ 1  2  3]
 [11 22 33]]
df_dict.values의 타입: <class 'numpy.ndarray'> df_dict.values shape:  (2, 3)


In [215]:
# DataFrame을 리스트로 변환
# tolist

list3 = df_dict.values.tolist()
print("df_dict.values.tolist() 타입:", type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
# to_dict

dict3 = df_dict.to_dict('list')
print("\n df_dict.to_dict(): 타입", type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict(): 타입 <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [216]:
titanic_df["Age_0"] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [217]:
titanic_df["Age_by_10"] = titanic_df["Age"]*10
titanic_df["Family_No"] = titanic_df["SibSp"] + titanic_df["Parch"] + 1
titanic_df.head()

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1
3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S      0      350.0          2
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S      0      350.0          1

In [218]:
titanic_df["Age_by_10"] = titanic_df["Age_by_10"] +100
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

## DataFrame에서 데이터 삭제

In [219]:
titanic_drop_df = titanic_df.drop("Age_0", axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

In [220]:
# inplace를 True로 둬야 영구적으로 삭제가 됨.
drop_result = titanic_df.drop(["Age_0", "Age_by_10", "Family_No"],
                             axis=1, inplace = True)
print("inplace=True로 drop 후 반환된 값:", drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값: None


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [221]:
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", 15)
print("\n ### before axis 0 drop ### \n")
print(titanic_df.head(3))
titanic_df.drop([0,1,2], axis=0, inplace=True)
print("\n ### after axis 0 drop ### \n")
print(titanic_df.head(3))


 ### before axis 0 drop ### 

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

 ### after axis 0 drop ### 

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


In [226]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv("../파이썬_머신러닝_완벽가이드/titanic/train.csv")
#index 객체 추출
indexes = titanic_df.index
print(indexes)
# Index 객체를 실제 값 array로 변환
print("Index 객체 array깂:\n", indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array깂:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232

In [227]:
# index별 슬라이싱 가능
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [228]:
# 한 번 만들어진 DataFrame 및 Series의 Index 객체는 함부로 변경할 수 없음.
# indexes[0] = 5

TypeError: Index does not support mutable operations