# Ch1. 파이썬 기반의 머신러닝과 생태계 이해

### 1. 머신러닝의 개념

일반적으로 머신러닝은 지도학습과 비지도학습, 강화학습으로 나뉜다

### 2. 머신러닝의 분류

### 3. 넘파이

In [12]:
import numpy as np

In [20]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array형태 : ', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array형태 :  (3,)


다음을 통해 1차원 배열을 생성할 수 있었고, 해당 배열의 타입(ndarray)과 shape(차원)에 대해 확인할 수 있었다.

다음은 2차원 배열에 대한 예시이다.

In [21]:
array2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print('array2 type:', type(array2))
print('array2 array형태 : ', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array형태 :  (2, 3)


여기서 체크해두면 좋을 점은 ndarray.shape는 ndarray의 차원과 크기를 튜플(tuple)형태로 나타내 준다는 것이다.

In [23]:
print('array1 : {0}차원, array2 : {1}차원'.format(array1.ndim, array2.ndim))

array1 : 1차원, array2 : 2차원


다음과 같이 어떠한 배열이 몇차원을 가지고 있는지 아는 것이 중요하다.

다음은 ndarray의 데이터 타입이다. 우리가 여기서 주의해야할 점은 ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다는 것이다. 즉, 한 개의 ndarray객체에 int와 float이 함께 있을 수 없다.

In [25]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


다음과 같이 list2가 array2로 변환되면서 int값들이 문자열들로 변화되었음을 알 수 있다.
또한, list3의 경우에도 array3로 변환되면서 int값들이 float으로 변환되었음을 알 수 있다.

ndarray내 데이터값의 타입 변경또한 astype()을 통해 가능하다. 이는 메모리 절약에 사용된다. 

In [31]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우, arange(), zeros(), ones()를 이용해 쉽게 ndarray를 생성할 수 있다.

In [33]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


reshape()메서드에 대해서도 우리가 인지해야 할 필요가 있는데, ndarray를 특정 차원 및 크기로 변환하기 때문이다.
여기서 기억해야 할 부분은 reshape()에 -1값을 인자로 적용한 경우라 생각하였다.

In [37]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
array3 = array1.reshape(-1, 3)
print(array3)

ValueError: cannot reshape array of size 10 into shape (3)

다음과 같이 (-1, 5)를 인자로 가진 경우에는 컬럼갯수 5개와 호환되는 shape로 자동변환한다. 하지만, (-1, 3)을 인자로 입력하게 되면 3으로 나눌 수 없기 때문에 valueError가 발생한다.

넘파이에서 행렬의 정렬에는 sort()와 argsort()가 사용된다. 차이점은 np.sort()는 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환하며, ndarray.sort()는 원 행렬 자체를 정렬한 형태로 반환하며 반환 값은 None이다.

In [44]:
org_array = np.array([3, 1, 5, 9])
sort_array1 = np.sort(org_array)
print(org_array, sort_array1)

[3 1 5 9] [1 3 5 9]


In [45]:
sort_array2 = org_array.sort()
print(org_array, sort_array2)

[1 3 5 9] None


다음과 같이 .sort()의 경우에는 원 행렬이 정렬되고 반환 값이 없음을 확인할 수 있다.

### 4. 데이터 핸들링 - 판다스

In [48]:
import pandas as pd
titanic_df = pd.read_csv('titanic/dataset/train.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [51]:
print(type(titanic_df))
# 타입이 dataaframe을 확인할 수 있다.

<class 'pandas.core.frame.DataFrame'>


In [52]:
print('DataFrame 크기 :', titanic_df.shape)

DataFrame 크기 : (891, 12)


In [53]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


우리가 해당 파트에서 기억해야 할 부분은 index, series, dataframe이다. 어떠한 형태를 가지고 있는지에 따라 사용할 수 있는 함수들도 정해져 있기 때문이다.ㅡ

예로는, value_counts()메서드는 Series객체에서만 정의되어 있다. 따라서 DataFrame은 value_counts()메서드를 가지고 있지 않다. 

In [55]:
value_counts = titanic_df['Pclass'].value_counts()
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

또한 여기서 중요한 점은 인덱스는 고유성이 보장된다면 의미 있는 데이터값 할당이 가능하다는 것이다.

In [56]:
value_counts1 = titanic_df['Pclass'].value_counts()
print(type(value_counts1))
print(value_counts1)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


다음은 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하는 방법이다.

In [62]:
import numpy as np

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
print()
df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3

1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


위에서는 1차원 형태의 데이터를 기반으로 데이터프레임을 생성하였다. 이번에는 2차원 형태의 데이터를 기반으로 데이터프레임을 생성해보겠다.

In [64]:
col_name2 = ['col1', 'col2', 'col3']

list2 = [[1, 2, 3],
        [11, 12, 13]]

array2 = np.array(list2)
print('array2 shape:', array2.shape)
df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
print()
df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


다음으로는 DataFrame의 컬렘 데이터 세트 생성 및 수정에 대해서 알아보자.

In [65]:
titanic_df['Age_0'] = 0
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  
3      0            113803  53.1000  C123        S      0  
4      0            373450   8.0500   NaN        S      0

이처럼 Age_0이라는 컬럼이 새로 생긴것을 확인할 수 있다. 여러 방법을 통해 컬럼 값을 일괄적으로 업데이트 또한 가능하다.

이보다는 DataFrame삭제 방법에 대해서 눈여겨봐야 한다고 생각되는데, 데이터 삭제에서 중요한 파라미터는 labels, axis, inplace이다.

In [66]:
titanic_drop_df = titanic_df.drop('Age_0', axis = 1)

In [67]:
titanic_drop_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

다음과 같이 Age_0컬럼이 삭제되었음을 알 수 있다. 여기서 axis를 1로 설정하였기 때문에 컬럼 방향으로 설정된 것이라는 것을 알아야 한다.

In [69]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  
3      0            113803  53.1000  C123        S      0  
4      0            373450   8.0500   NaN        S      0

하지만, 중요한 점은 원 데이터에서 Age_0은 삭제되지 않았다는 것이다. 그 이유는 inplace 파라미터의 dafalut값이 False이기 때문.

In [70]:
drop_result = titanic_df.drop('Age_0', axis=1, inplace = True)
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

이를 통해 inplace값을 True로 설정하면 원 데이터에서 삭제됨을 알 수 있다.

DataFrame과 Series의 정렬을 위해서는 sort_values()메서드가 사용된다. 여기서의 주요 입력 파라미터는 by, ascending, inplace이다.

In [73]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass                              Name     Sex  \
845          846         0       3               Abbing, Mr. Anthony    male   
746          747         0       3       Abbott, Mr. Rossmore Edward    male   
279          280         1       3  Abbott, Mrs. Stanton (Rosa Hunt)  female   

      Age  SibSp  Parch     Ticket   Fare Cabin Embarked  
845  42.0      0      0  C.A. 5547   7.55   NaN        S  
746  16.0      1      1  C.A. 2673  20.25   NaN        S  
279  35.0      1      1  C.A. 2673  20.25   NaN        S

다음과 같이 titanic_df를 Name컬럼으로 오름차순 정렬 반환했음을 알 수 있다.

In [74]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [75]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

다음은 모든 컬럼 및 특정 컬럼에 aggregationㅍ함수를 적용한 결과이다.

groupby()를 적용해보자. groupby()사용 시 입력 파라미터 by에 칼럼을 입력하면 대상 칼럼으로 groupby된다.

In [77]:
titanic_groupby = titanic_df.groupby(by = 'Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [78]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [80]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

다음은 결손 데이터 처리에 대해서 다루어보자.

In [81]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

In [82]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

이처럼 결손데이터 여부를 isna()를 통해 확인할 수 있고, fillna()를 통해 결손 데이터를 대체할 수 있다.

In [83]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

### 5. 정리

# Ch2. 사이킷런으로 시작하는 머신러닝

### 2. 첫 번째 머신러닝 만들어 보기

In [88]:
import pandas as pd

iris = load_iris()

iris_data = iris.data

iris_label = iris.target
print('iris targer값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

iris targer값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

train_test_split()을 통해 학습용 데이터와 테스트용 데이터를 분리해 볼 수 있다.

In [89]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)

NameError: name 'train_test_split' is not defined

In [90]:
# 오류 발생으로 인해 객체 생성 생략

### 3. 사이킷런의 기반 프레임워크 익히기

Estomator클래스에서는 fit()과 predict()를 내부에서 구현하고 있다. 

In [91]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [92]:
keys = iris_data.keys()
print('붗꽃 데이터 세트의 키들:', keys)

붗꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [94]:
print(type(iris_data.feature_names))
print(len(iris_data.feature_names))
print(iris_data.feature_names)

print(type(iris_data.target_names))
print(len(iris_data.target_names))
print(iris_data.target_names)

<class 'list'>
4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
<class 'numpy.ndarray'>
3
['setosa' 'versicolor' 'virginica']


다음은 load_iris()가 반환하는 객체의 키인 feature_names, target_name, data, target이 가리키는 값들을 출력한 결과이다.

### 4. Model Selection 모듈 소개

학습에 있어서 우리는 train_test_split()을 이용해야 한다. 그 이유는 동일한 학습 및 예측 데이터 셋을 사용하게 되면 예측 정확도가 1로 계산도기 때문이다. 따라서 대표적으로 7대 3의 비율로 데이터를 분리하고, random_state를 설정하여 데이터 세트를 변화시키는 것이 일반적이다.

In [95]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.3, random_state = 121)

In [98]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print(accuracy_score(y_test, pred))

0.9555555555555556


과적합(Overfitting)을 방지하기 위한 방법 중 하나로 교차 검증이 존재한다. 교차 검증은 데이터 편중을 막기 위해서 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행하는 것이다. 